---
name: Lint and test
on: [push]

concurrency:
    group: pr-${{ github.ref }}
    cancel-in-progress: true

jobs:
    golangci:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 - https://github.com/actions/checkout/releases

            - name: Set up Go
              uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0 - https://github.com/actions/setup-go/releases
              with:
                  go-version-file: go.mod

            - name: Run GolangCI-Lint Scanner
              uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0 - https://github.com/golangci/golangci-lint-action/releases
              with:
                  version: v2.4.0 # renovate: datasource=github-releases,depName=golangci/golangci-lint

    test:
        name: Test and coverage
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 - https://github.com/actions/checkout/releases

            - name: Set up Go
              uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0 - https://github.com/actions/setup-go/releases
              with:
                  go-version-file: go.mod

            - name: Run Unit tests.
              run: |
                go install golang.org/x/tools/cmd/deadcode@latest
                make test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1 - https://github.com/codecov/codecov-action/releases
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.out
                  # Notify us when failed, so devs are not waiting for Codecov report when it will never come.
                  # Because Codecov report is required to be able to merge, we have to run again the whole test anyway.
                  fail_ci_if_error: true
